version: '3'

services:
  crontab-ui:
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    command: ["sh", "-c", 'DEBUG="express:*" node /crontab-ui/app.js']
    volumes:
      - .:/crontab-ui/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.ssh/:/root/.ssh/
    ports:
      - 8000:8000
